spring:
  profiles: default

zuul:
  routes:
    management:
      path: /management/**
      url: http://management:8083/management
      service-id: /management/**

    attendance:
      path: /attendance/**
      url: http://attendance:8081/attendance
      service-id: /attendance/**

    salary:
      path: /salary/**
      url: http://salary:8082/salary
      service-id: /salary/**
